name: flutter_subm2_getx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.4
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^4.6.6
  http: ^1.1.2
  cached_network_image: ^3.3.0
  # connectivity: ^3.0.6
  connectivity_plus: ^5.0.2
  # connectivity_plus: ^3.0.6

flutter:
  uses-material-design: true
