name: flutter_subm2_getx
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # json_serializable: ^6.1.4
  json_serializable: ^6.7.1
  google_fonts: ^6.1.0
  get: ^4.6.6
  http: ^1.1.2
  get_storage: ^2.1.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  flutter_local_notifications: ^16.3.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
  - assets/
